#!/bin/bash

vendor=adobe
font=MinionPro

dir=$1

if [ "x$dir" = x ]
then
  dir=$(kpsewhich -expand-var='$TEXMFLOCAL')
fi

if [ -d "$dir/fonts/enc" ]
then
  # new directory layout
  enc_dir="$dir/fonts/enc/dvips/$font"
  map_dir="$dir/fonts/map/dvips/$font"
  pfb_dir="$dir/fonts/type1/$vendor/$font"
  tfm_dir="$dir/fonts/tfm/$vendor/$font"
  vf_dir="$dir/fonts/vf/$vendor/$font"
  tex_dir="$dir/tex/latex/$font"
else
  # old directory layout
  enc_dir="$dir/dvips/$font"
  map_dir="$dir/dvips/$font"
  pfb_dir="$dir/fonts/type1/$vendor/$font"
  tfm_dir="$dir/fonts/tfm/$vendor/$font"
  vf_dir="$dir/fonts/vf/$vendor/$font"
  tex_dir="$dir/tex/latex/$font"
fi

mkdir -p "$enc_dir" "$map_dir" "$pfb_dir" "$tfm_dir" "$vf_dir" "$tex_dir"

cp pfb/*.pfb         "$pfb_dir"
cp dvips/*.enc       "$enc_dir"
cp dvips/$font.map   "$map_dir"

# copy TFM and VF in several batches

cp tfm/MnSymbol*.tfm "$tfm_dir"
cp vf/MnSymbol*.vf   "$vf_dir"

cp tfm/*orn*.tfm "$tfm_dir"

for x in tosf tlf osf lf
do
  cp tfm/*$x*.tfm "$tfm_dir"
  cp vf/*$x*.vf   "$vf_dir"
done

mktexlsr

