#!/bin/bash

mkdir -p pfb tfm vf dvips

echo "Creating PostScript fonts ..."

for font in otf/*.otf
do
  cfftot1 $font $(basename $font .otf).pfb
done
for font in *.pfb
do
  t1dotlessj $font $(basename $font .pfb)LCDFJ.pfb
done

echo "Creating TeX metrics ..."

./scripts/maketfm MinionPro "$*" | grep -v '^I had to' | sort -u >dvips/MinionPro.map

mv *.pfb pfb

#for v in *.pl
#do
#  if [ -e "$v" ]
#  then
#    pltotf "$v"
#  fi
#done
#
#for v in *.vpl
#do
#  if [ -e "$v" ]
#  then
#    vptovf "$v"
#  fi
#done

(cd fontinst; ../scripts/makeint MinionPro)

(cd tex; latex MinionPro.ins)

