#!/bin/sh

font=$1

if [ "x$font" = "x" ]
then
  echo "No font specified!";
  echo "USAGE: maketfm <font>";
  exit 1
fi

for s in 5 6 7 8 9 10 12
do
  if [ ! -e MnSymbolF$s.pl ]
  then
    mktextfm MnSymbolF$s
    tftopl MnSymbolF$s.tfm MnSymbolF$s.pl
  fi
  if [ ! -e MnSymbolF-Bold$s.pl ]
  then
    mktextfm MnSymbolF-Bold$s
    tftopl MnSymbolF-Bold$s.tfm MnSymbolF-Bold$s.pl
  fi
done

tftopl ../tfm/$font-It-osf-oml--base.tfm        $font-It-osf-oml--base.pl
tftopl ../tfm/$font-It-osf-cn2-integral.tfm     $font-It-osf-cn2-integral.pl
tftopl ../tfm/$font-BoldIt-osf-oml--base.tfm    $font-BoldIt-osf-oml--base.pl
tftopl ../tfm/$font-BoldIt-osf-cn2-integral.tfm $font-BoldIt-osf-cn2-integral.pl

tex make-MnSymbolFI-noopt.tex

if [ -e ../tfm/$font-SemiboldIt-osf-oml--base.tfm ]
then
  tftopl ../tfm/$font-SemiboldIt-osf-oml--base.tfm    $font-SemiboldIt-osf-oml--base.pl
  tftopl ../tfm/$font-SemiboldIt-osf-cn2-integral.tfm $font-SemiboldIt-osf-cn2-integral.pl

  tex make-MnSymbolFI-noopt-sb.tex
fi


if [ -e ../tfm/$font-ItDisp-osf-cn1-integral.tfm ]
then
  tftopl ../tfm/$font-ItDisp-osf-cn1-integral.tfm         $font-ItDisp-osf-cn1-integral.pl
  tftopl ../tfm/$font-SemiboldItDisp-osf-cn1-integral.tfm $font-SemiboldItDisp-osf-cn1-integral.pl
  tftopl ../tfm/$font-BoldItDisp-osf-cn1-integral.tfm     $font-BoldItDisp-osf-cn1-integral.pl

  tex make-MnSymbolFI.tex
fi

for v in *.vpl
do
  vptovf $v
done

mv *.vf  ../vf
mv *.tfm ../tfm

