#!/bin/bash

if [ ! -e MnSymbolF10.pl ]
then
  tftopl MnSymbolF10.tfm MnSymbolF10.pl
fi

tftopl ../tfm/MinionPro-It-osf-oml--base.tfm        MinionPro-It-osf-oml--base.pl
tftopl ../tfm/MinionPro-It-osf-cn2-integral.tfm     MinionPro-It-osf-cn2-integral.pl
tftopl ../tfm/MinionPro-ItDisp-osf-cn1-integral.tfm MinionPro-ItDisp-osf-cn1-integral.pl

tex make-MnSymbolFI.tex

for v in *.vpl
do
  vptovf $v
done

mv *.vf ../vf
mv *.tfm ../tfm
