#!/bin/bash

for s in 5 6 7 8 9 10 12
do
  if [ ! -e MnSymbolF$s.pl ]
  then
    tftopl MnSymbolF$s.tfm MnSymbolF$s.pl
  fi
  if [ ! -e MnSymbolF-Bold$s.pl ]
  then
    tftopl MnSymbolF-Bold$s.tfm MnSymbolF-Bold$s.pl
  fi
done

tftopl ../tfm/MinionPro-It-osf-oml--base.tfm        MinionPro-It-osf-oml--base.pl
tftopl ../tfm/MinionPro-It-osf-cn2-integral.tfm     MinionPro-It-osf-cn2-integral.pl
tftopl ../tfm/MinionPro-ItDisp-osf-cn1-integral.tfm MinionPro-ItDisp-osf-cn1-integral.pl

tex make-MnSymbolFI.tex

for v in *.vpl
do
  vptovf $v
done

mv *.vf  ../vf
mv *.tfm ../tfm

