#!/bin/bash

mkdir -p pfb pl tfm vf vpl dvips

echo "Creating PostScript fonts ..."

for font in otf/*.otf
do
  cfftot1 $font $(basename $font .otf).pfb
done
for font in *.pfb
do
  t1dotlessj $font $(basename $font .pfb)LCDFJ.pfb
done

echo "Creating TeX metrics ..."

./scripts/maketfm MinionPro | sort | uniq >dvips/Minion.map

for v in *.pl
do
  if [ -e "$v" ]
  then
    pltotf "$v"
  fi
done

for v in *.vpl
do
  if [ -e "$v" ]
  then
    vptovf "$v"
  fi
done

mv a_*.enc    dvips
mv *.pl       pl
mv *.pfb      pfb
mv *.vf       vf
mv *.vpl      vpl
mv *base*.tfm tfm   # Split this move in two parts as the arg. list is too large.
mv *.tfm      tfm

