#!/bin/bash

mkdir -p afm pfb tfm vf vpl

for f in otf/*.otf
do
  ./scripts/fonttopfb.pe $f
done

mv otf/*.pfb pfb
mv otf/*.afm afm

./scripts/maketfm MinionPro | sed -e 's!dvips/!!g' -e 's!^[^ ]* \([^ ]*\) .*$!\0 <\1.pfb!' >dvips/Minion.map

for v in vpl/*.vpl
do
  vptovf $v
done

mv *.tfm tfm

# we only need the VF-files with increased letterspacing
mv *L*.vf *SSC*.vf vf
rm *.vf

