#!/bin/bash
# generate shift values for capital accents in the TS1 encoding
for i in *.afm;do
  cat $i|egrep " grave | grave.cap "              |gawk ' / grave / {lowy=$12}        / grave.cap /        {print "% POSITION Grave 0 "lowy-$12" 0"}'>kerning/`echo $i|sed s/"MinionPro-"//g|sed s/".afm"//g`-ts1.kern
  cat $i|egrep " acute | acute.cap "              |gawk ' / acute / {lowy=$12}        / acute.cap /        {print "% POSITION Acute 0 "lowy-$12" 0"}'>>kerning/`echo $i|sed s/"MinionPro-"//g|sed s/".afm"//g`-ts1.kern
  cat $i|egrep " circumflex | uniEFF7 "           |gawk ' / circumflex / {lowy=$12}   / uniEFF7 /          {print "% POSITION uniEFF7 0 "lowy-$12" 0"}'>>kerning/`echo $i|sed s/"MinionPro-"//g|sed s/".afm"//g`-ts1.kern
  cat $i|egrep " tilde | uniEFF5 "                |gawk ' / tilde / {lowy=$12}        / uniEFF5 /          {print "% POSITION uniEFF5 0 "lowy-$12" 0"}'>>kerning/`echo $i|sed s/"MinionPro-"//g|sed s/".afm"//g`-ts1.kern
  cat $i|egrep " dieresis | dieresis.cap "        |gawk ' / dieresis / {lowy=$12}     / dieresis.cap /     {print "% POSITION Dieresis 0 "lowy-$12" 0"}'>>kerning/`echo $i|sed s/"MinionPro-"//g|sed s/".afm"//g`-ts1.kern
  cat $i|egrep " hungarumlaut | hungarumlaut.cap "|gawk ' / hungarumlaut / {lowy=$12} / hungarumlaut.cap / {print "% POSITION Hungarumlaut 0 "lowy-$12" 0"}'>>kerning/`echo $i|sed s/"MinionPro-"//g|sed s/".afm"//g`-ts1.kern
  cat $i|egrep " ring | uniEFF3 "                 |gawk ' / ring / {lowy=$12}         / uniEFF3 /          {print "% POSITION uniEFF3 0 "lowy-$12" 0"}'>>kerning/`echo $i|sed s/"MinionPro-"//g|sed s/".afm"//g`-ts1.kern
  cat $i|egrep " caron | caron.cap "              |gawk ' / caron / {lowy=$12}        / caron.cap /        {print "% POSITION Caron 0 "lowy-$12" 0"}'>>kerning/`echo $i|sed s/"MinionPro-"//g|sed s/".afm"//g`-ts1.kern
  cat $i|egrep " breve | uniEFEE "                |gawk ' / breve / {lowy=$12}        / uniEFEE /          {print "% POSITION uniEFEE 0 "lowy-$12" 0"}'>>kerning/`echo $i|sed s/"MinionPro-"//g|sed s/".afm"//g`-ts1.kern
  cat $i|egrep " macron | macron.cap "            |gawk ' / macron / {lowy=$12}       / macron.cap /       {print "% POSITION Macron 0 "lowy-$12" 0"}'>>kerning/`echo $i|sed s/"MinionPro-"//g|sed s/".afm"//g`-ts1.kern
  cat $i|egrep " dotaccent | uniEFED "            |gawk ' / dotaccent / {lowy=$12}    / uniEFED /          {print "% POSITION uniEFED 0 "lowy-$12" 0"}'>>kerning/`echo $i|sed s/"MinionPro-"//g|sed s/".afm"//g`-ts1.kern
done
